version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/laravel:/var/www
    depends_on:
      - php
  
  php:
    build: ./docker/php
    volumes:
      - ./src/laravel:/var/www
